### ISSUE TITLE
Memory leaking on Firefox

### ISSUE THREAD

**Issue by voidlynx** [slowlydev/f1-dash#108]
Heya, big fan of F1-Dash. Unfortunately, it absolutely destroys my system's memory on Firefox.
Experienced this on both my main desktop and laptop under latest version of Firefox for a few race weekends now.
Right now opened the dashboard in Yandex Browser (chromium-based) during Monaco FP1 and my memory is doing absolutely fine.
So I'm absolutely sure it's a Firefox bug that should be easily reproducable. Oh, also, the more my memory fills up, the higher the CPU usage is and the dashboard just freezes.

![Running on Yandex Browser (Chromium-based)](https://github.com/slowlydev/f1-dash/assets/59738161/8127657a-4f10-4ec2-9d1a-0971c4427fa2)

![Running on Firefox](https://github.com/slowlydev/f1-dash/assets/59738161/8c284405-0a95-4abd-8f6a-14378353a391)

**Comment by voidlynx** [comment]
Yeah the total sum seems to be going over a thousand, but it starts lagging hard even before it gets near that number.

![image](https://github.com/slowlydev/f1-dash/assets/59738161/28c09b69-3a3c-4b51-bd7d-2c9a82e5adfb)

**Comment by slowlydev** [comment]
Oh wow yeah, each buffer has a 1000 limit so we would be no where near the limits.
Has this issue always been there or was it introduced lately?

**Comment by voidlynx** [comment]
I'm not sure since how long ago, but it did occur when watching the Imola GP. Probably a few weeks before that too. Likely way before that, can't say for sure.

**Comment by slowlydev** [comment]
Hm I did not seem to get the excessive leak you did. But I was also using firefox nightly and I am on arm macOS. I will test on a windows machine next.   

<img width="1256" alt="image" src="https://github.com/slowlydev/f1-dash/assets/61624214/e735bad9-d877-4d85-8c55-f8f30b0c54df">

**Comment by simylein** [comment]
Maybe this pr #119 could be part of the solution?

**Comment by rikkuness** [comment]
I was able to reproduce this during Austria GP qualifying. It seemed to be proportional to the delay, if I had 0 delay there was no memory build up, I then set an ~45 second delay and the mem usage started to skyrocket, maxing out at around 16GB mem usage. I tried to capture a memory snapshot to try debug further but it was struggling to do once it had already exhausted all the resources.

![Screenshot_29](https://github.com/slowlydev/f1-dash/assets/3525311/3aedef85-0160-4854-96ce-f959c03b4d64)
![Screenshot_30](https://github.com/slowlydev/f1-dash/assets/3525311/91c174f2-3883-45a0-a643-905b0efbd3f5)
![Screenshot_31](https://github.com/slowlydev/f1-dash/assets/3525311/cfb49959-c122-49eb-8bcc-71adf653b2c3)

**Comment by slowlydev** [comment]
Thanks for the testing. Looks like the buffer changes did not fix the memory leaks.

> It seemed to be proportional to the delay, if I had 0 delay there was no memory build up, I then set an ~45 second delay and the mem usage started to skyrocket, maxing out at around 16GB mem usage.

Thats very weird, because the only difference between 0 and >0 delay is that the buffer will be searched and with 0 we just take latest. Also that it increases proportionally is weird as well.

> I tried to capture a memory snapshot to try debug further but it was struggling to do once it had already exhausted all the resources.

okay, I will try to get a snapshot on my windows machine

**Comment by rikkuness** [comment]
> Thats very weird, because the only difference between 0 and >0 delay is that the buffer will be searched and with 0 we just take latest. Also that it increases proportionally is weird as well.

It is entirely possible it was coincidental, but there were times where the behaviour was seemingly normal and then something caused it to suddenly climb until resources were exhausted 🤔

**Comment by WolfganP** [comment]
Same here on Firefox 130.0 on Linux. Long delays trigger memory leaks on my system.

**Comment by WolfganP** [comment]
Today I followed  Singapore's FP2 session on Brave (on linux) with a delay of 73secs and everything was stable.
Any troubleshooting info we can provide to help solve the memory issue in firefox?

**Comment by slowlydev** [comment]
The Firefox memory issues have been on https://dev.f1-dash.com and the fix will arrive in prod soon.
