### ISSUE TITLE
Possibility to add this to my app

### ISSUE THREAD

**Issue by BrightDV** [slowlydev/f1-dash#110]
Hello,
Since some years, I have made an [open-source app](https://github.com/BrightDV/BoxBox) to follow Formula 1.
When a session is running, it shows a live leaderboard, but for the moment I use the official one or another with fewer details (using WebViews).
I just found your website yesterday (which looks really, really good) and I wonder if you would agree that I add it to my app, as an alternative to the official one?
Thanks!

**Comment by slowlydev** [comment]
@BrightDV wow that's a neat app u got there! Sure, feel free to add it to your App!

**Comment by BrightDV** [comment]
Thanks!
