### ISSUE TITLE
Make text of days on the Schedule page bigger

### ISSUE THREAD

**Issue by SpatzlHD** [slowlydev/f1-dash#118]
I think it would be a great idea to make the text of days in the schedule slightly bigger then the text of what is happening. In my opinion it isnt really clear on the first view of the page to recognise that the day is a heading for the text below it 
![image](https://github.com/slowlydev/f1-dash/assets/79466158/87b63cb1-b3e5-4f98-b72a-26f3c6a95ed3)

**Comment by slowlydev** [comment]
I agree it's not perfect, I was struggling while designing & implementing it. Feel free to make some suggestions, but I feel like just using a font size in the middle isn't the best solution.

**Comment by shashwatah** [comment]
Hey, I tried the app during the British GP, and was very impressed, then I stumbled upon this issue. 

This is what I was able to come up with as a solution: 

![gp-schedule-redone](https://github.com/user-attachments/assets/6d1908fa-bbd0-4c1a-a80a-d6a9ed77e478)

I added equal whitespace between the day headings and the elements above and below them, slightly increased the font size, switched font weight from regular to semi-bold, and changed to font color to #52525b (same as the timings).

Do tell if this is any good, I would love to contribute!

**Comment by slowlydev** [comment]
Hey @shashwatah Not bad, I thought maybe "text-white text-xl" might also look good.

**Comment by shashwatah** [comment]
Hey, the previous mockup I sent was made with XD. These were done with tailwind:

"text-white text-xl my-3":
![schedule-text-white](https://github.com/user-attachments/assets/bd6ea1da-a72c-41ff-b173-9451baf11434)

"text-zinc-600 text-lg font-semibold my-3":
![schedule-text-zinc](https://github.com/user-attachments/assets/a51d51a8-023c-4bb9-9919-10afe971e8fe)

In my opinion both the options work well. Although, I felt that "text-white" doesn't help distinguish the heading at a glance very well. Could you choose between the two? I'll submit a PR then after.

**Comment by slowlydev** [comment]
Hey @shashwatah thanks a lot of the 2 screenshots. 🙏🏻 I agree it's a bit more difficult with the white but I think thats the way to go for now. If it's not good enough we could maybe make it semibold or something. Looking forward to the PR 🚀

**Comment by shashwatah** [comment]
Hey @slowlydev, I've made a PR (#137). I wasn't sure what title to use for the commit and branch for a minor style change, so I used "fix". I hope that's okay.
