### ISSUE TITLE
Advanced/custom mode personal best sectors are always purple

### ISSUE THREAD

**Issue by AntoniosBarotsis** [slowlydev/f1-dash#139]
As the title states:
![image](https://github.com/user-attachments/assets/26c29f13-447a-483b-aa91-3489bb213a21)

Not sure if this is intentional but it would make more sense for the overall best to be purple. I'm not sure if [this bit is relevant](https://github.com/slowlydev/f1-dash/blob/8ef970c36d7a43b012fe62ebd8603713ef1f8638/dash/src/components/driver/Driver.tsx#L89) perhaps. I didn't take too good a look but perhaps something similar to [this](https://github.com/slowlydev/f1-dash/blob/8ef970c36d7a43b012fe62ebd8603713ef1f8638/dash/src/components/driver/Driver.tsx#L56)  could be done for each sector.

**Comment by AntoniosBarotsis** [comment]
Ok upon a slightly further look it looks like the data isn't already there so you'd have to keep a <driver, best s1,s2,s3> table being updated which sounds more annoying to implement 🗿

**Comment by slowlydev** [comment]
Ah, right they have the wrong color the whole time, I will adjust this as soon as I have time.
