### ISSUE TITLE
High delays not supported

### ISSUE THREAD

**Issue by Woolie29** [slowlydev/f1-dash#146]
There appears to be some sort of limit on how long the delay can be (unclear what this limit is). When I try to enter, say, 90 or 120 seconds delay, I get the syncing message but the counter just keeps on jumping back up over and over again and I never get back to the dashboard. On smaller delays it works OK for the most part, although it does seem to need to re-sync fairly often which can be frustrating.

**Comment by slowlydev** [comment]
Yep high delays are currently not supported, but I am working on it.
I have not noticed anything in the lower delays with re-syncing :(

**Comment by Woolie29** [comment]
Thanks for responding. I thought that might be the case, it just didn't say anything on the site. With the lower delays, perhaps I was close to the limit and it was just dropping in and out.

**Comment by Mighty-Eagle27** [comment]
Just to add on to that in detail, such high delays cause the dashboard (essentially the whole program) to freeze. Sometimes it freezes for around 10-30 seconds, catches up only to freeze once again.

Any specifics on why that issue might exist?

**Comment by marcossaba** [comment]
> Just to add on to that in detail, such high delays cause the dashboard (essentially the whole program) to freeze. Sometimes it freezes for around 10-30 seconds, catches up only to freeze once again.
> 
> Any specifics on why that issue might exist?

+1 on this. In my case, this freeze happens only on my iPad (air M2), but when using my laptop this issue does not reproduce. In both scenarios I'm using Google Chrome. Side note, on the iPad this reproduces on Safari too.

Let me know if I can help any further with testing and/or data. 

Love this app

**Comment by slowlydev** [comment]
Yeah so that issue @Mighty-Eagle27 and @marcossaba are describing is something different from the original issue. The original issue was about f1-dash not supporting delays up to the 100s mark. That should work these days. The other issues you guys are describing are performance issues as f1-dash the website starts lagging after a certain amount of time. THats also why on mobile devices its more apparent than on desktop/laptops.

**Comment by slowlydev** [comment]
I opend a new issue to track this as the high delays itself are supported now. New issue: #168
