### ISSUE TITLE
Live server seems offline

### ISSUE THREAD

**Issue by sbehrends** [slowlydev/f1-dash#166]
During Q2 of Mexico race, the live server seems went out.
`https://live-backend.f1-dash.com/api/sse` timeout and dashboard never loaded.

**Comment by sbehrends** [comment]
`https://live-backend.f1-dash.com/api/health` endpoint was returning `{"success":true}` so looks like the server was up, although no data from `sse`.

The `formula1.com` live server seems it was up, so I guess that was not the reason for `sse` to now return state.

Now on Q3 it returned, but then it lost connection again.

**Comment by slowlydev** [comment]
I personally didn't have any issues, let me know if it happens again

**Comment by sbehrends** [comment]
During today race it happened again. Tried multiple browser and incognito. Could be some high traffic issues?

**Comment by sbehrends** [comment]
I am not related to this channel, but while browsing YouTube found this stream that seems to be using this Project. 

Around this [time](https://www.youtube.com/live/kY7yjtdSv_Q?t=8641&si=3yfCC2xCdp9leI8i) seems like the face a similar issue and they fallback for a alternative project. 

This may be proof that some other visitors are having similar problems.

**Comment by slowlydev** [comment]
Hm okay, I changed some config stuff. I feel like this is a throttling issue as I am not experiencing it. Lets see if its better in the next session

**Comment by sbehrends** [comment]
Cool! Amazing project!
