### ISSUE TITLE
Add wakelock for mobile/laptop devices

### ISSUE THREAD

**Issue by Marocco2** [slowlydev/f1-dash#170]
I use iPad when I watch the race on my TV but it will turn off the screen according to system settings.
Could you add a wakelock so mobile/laptop devices won't turn off the display?

Thanks

**Comment by slowlydev** [comment]
Great idea, will do :)

**Comment by slowlydev** [comment]
Its implemented & live on https://dev.f1-dash.com will arrive in prod soon.
