### ISSUE TITLE
[Bug] Safety Car does not move on the track map

### ISSUE THREAD

**Issue by Ben569483** [slowlydev/f1-dash#171]
Whenever the safety car is deployed, it shows up on the driver tracker map but doesn't move at all.
![image](https://github.com/user-attachments/assets/938bf89a-58fa-4661-96fd-adc0e3b70258)

**Comment by slowlydev** [comment]
Yep, I thought I have the data, but its not changing and stays at 0, 0, 0 so I am gonna remove it again, but thanks for the issue.
