### ISSUE TITLE
Display the app version somewhere

### ISSUE THREAD

**Issue by WolfganP** [slowlydev/f1-dash#176]
To easier the tracking of issues and tests, I suggest to display the app version running (main screen or in an about / config section, maybe also differentiating between dev and prod), to make sure that any bug reports is related to the latest version.
Thanks as always for this!

**Comment by slowlydev** [comment]
Yep I have been putting of releases and version numbers, definitely should start doing this as its getting more popular.

**Comment by slowlydev** [comment]
Live on https://dev.f1-dash.com
