### ISSUE TITLE
Delay Feature Not Applied to All Elements (Safety Car, Race Director Messages, Flags)

### ISSUE THREAD

**Issue by 07manan** [slowlydev/f1-dash#194]
Hi @slowlydev,

First of all, great work on this project!

I was using the dashboard during the Qatar GP this past weekend, and noticed that while the delay feature (which is a really cool addition!) worked well for syncing my data to the stream, there was an issue with how it was applied to certain elements. Specifically, when a safety car was deployed, the dashboard showed the safety car status as active before it was deployed on the stream, indicating that the delay wasn't applied to this status or to race director messages. Additionally, I’m not sure about flags, but they might also not have been delayed.

It would be great to see the delay feature applied consistently across all elements to enhance the sync accuracy. 

This is an awesome project, and I’d love to contribute to it. Let me know if I can help fix this bug or assist with any other improvements!

Thanks!

**Comment by slowlydev** [comment]
Tbh I am not quite sure if this one was on f1-dash side or just f1 in general. The race control feed shows a constant switching between states so it was a bit messy from their side.

But I will keep an eye out for de-synch.
