### ISSUE TITLE
First stint marked as 0

### ISSUE THREAD

**Issue by AdriCardenas** [Slowlydev/f1-dash#54]
Watching de stint of the drivers i have seen that the first stint is marked as 0. It should be marked as stint 1, right?

![image](https://github.com/Slowlydev/f1-dash/assets/27868425/88c658e2-98a3-4684-9821-22cd5e5ca418)

**Comment by Slowlydev** [comment]
It's the first stint correct. But I wanted to display Pit Stops, and "St" was for "**St**ops". But as it seems confusing maybe "pit" would've been better. What's your opinion?

**Comment by Slowlydev** [comment]
Okay yeah, if u want to u can open a PR if u want to do it right now. But I would also do it when touching the frontend for V2, but that might take a while. Or what do you think?

**Comment by AdriCardenas** [comment]
> Okay yeah, if u want to u can open a PR if u want to do it right now. But I would also do it when touching the frontend for V2, but that might take a while. Or what do you think?

Not really important. If you will update in the V2 version probably can mark first PIT like "PIT 1", "PIT 2"...
