### ISSUE TITLE
Driver Laptime History

### ISSUE THREAD

**Issue by Xi4tu** [Slowlydev/f1-dash#55]
Hi, is it possible to review all lap times of a given driver? I couldn't find this feature, and I believe it would be a valuable addition. Also it will be amazing to compare all laps in a chart.

**Comment by Slowlydev** [comment]
Hello there, thanks for the Issue!
Right now there is no such feature, but I definitely agree that it is a valuable addition. 
I am currently working on v2, which enables you to click the driver and then see a graphs under a driver like this, wich would include lap time:

<img width="724" alt="Driver Extended" src="https://github.com/Slowlydev/f1-dash/assets/61624214/6a0ae871-719b-4860-90b5-e6ac7d6fd193">

But a dedicated page would be great too, but haven't really thought about how it should look and be like.

**Comment by Xi4tu** [comment]
Nice, it looks so good!.
