### ISSUE TITLE
DRS Enabled all the time

### ISSUE THREAD

**Issue by AdriCardenas** [slowlydev/f1-dash#56]
I have been checking the DRS status in the UI and is always enabled. I don't know if this is a bug. In this screenshot you can see that is enabled in a position without DRS.
![image](https://github.com/Slowlydev/f1-dash/assets/27868425/8edeb9b2-480d-4e62-9d4e-0dc67499941a)

PD: I have seen that the live timing is stopping in the first practice

**Comment by Slowlydev** [comment]
About DRS, oh yeah true, not sure why this is, maybe the merging of data put itself into a state where its stuck on drs on.

And Yes I am currently facing multiple issues, like bandwidth and crashes of the backend.
