### ISSUE TITLE
Access previous race data for feature work

### ISSUE THREAD

**Issue by jay-khatri** [Slowlydev/f1-dash#64]
I'm trying to look into the code base to simulate a race using some local data, but I can't seem to access the data from a recent race using the the script in `data-saver` (the data returned isn't for the whole race). Can I only access this data during a race? And if so, is there a place we can access the archive data from the instance that you're running?

**Comment by Slowlydev** [comment]
Thanks for the issue!
Yeah that's correct, `data-saver` 'only saves data' when a session is currently ongoing.
Here are some 'saves/recordings' I did for when I am developing.

https://github.com/Slowlydev/f1-dash-data-parser/releases/tag/data

With those u can use `data-simulator` which starts a WebSocket Server and reads those files line-by-line and sends them with a semi random delay (10-200ms). I hope this helps :)
