### ISSUE TITLE
Website does not show any data

### ISSUE THREAD

**Issue by Roky3029** [Slowlydev/f1-dash#67]
I don't know why but whenever I try to access the page it keeps infinitedly loading and I can't access the data. I tried, though, to access it a couple of hours ago and I could, but I try now and nothing. 
I don't believe it's a problem related to my Internet connection as I got it connected via Ethernet cable.
![imagen](https://github.com/Slowlydev/f1-dash/assets/75387461/c5a7daba-ff0d-461d-b737-4ff9013eea9c)
This is what I get everytime I go to the page and no matter the times I refresh, it won't load

**Comment by Slowlydev** [comment]
Hey there, thanks for the issue. 
I'm pretty sure this is related and covered by #57

But yeah I am aware that sometimes it doesn't load, lag behind, disconnect or doesn't even connect.
