### ISSUE TITLE
Old race info should be reset

### ISSUE THREAD

**Issue by AdriCardenas** [slowlydev/f1-dash#74]
I checked live timing when first practice session started. I have seen that the information from the previous race has not been reset. I think that is a small bug in the front.

You can check here the info in the screenchot.
1.  Position change at the start of the Row
2.  Race laps counter
3.  Team radios messages
4.  Race info messages

![image](https://github.com/Slowlydev/f1-dash/assets/27868425/c2e137e1-ff4a-4238-8d3e-91ed1dce6e84)

**Comment by Slowlydev** [comment]
Yeah it's been an issue since day 1. As I am not quite sure when to reset the state. 

I also think mini sectors are also affected, in the screen shot there are a lot of yellow mini sectors at the same place for every driver.

**Comment by slowlydev** [comment]
I think this got closed by #101 and it seems to be working for the past 2 weeks.
