### ISSUE TITLE
[BUG] Next Race Info Incorrect

### ISSUE THREAD

**Issue by Aarekaz** [slowlydev/f1-dash#81]
The next race info on the home page shows Australia which is incorrect. It should show Japan

![image](https://github.com/slowlydev/f1-dash/assets/36888347/13da895d-d7f6-4568-85fe-28abcc5c4292)

**Comment by slowlydev** [comment]
Thanks for the Issue, yes the page is buggy and I reworked it in v2, checkout the [current implementation here](https://v2.f1-dash.com/schedule) its now just showing the schedule, as the archive replay  functionality is not implemented yet.

**Comment by Aarekaz** [comment]
This looks awsomeee!
